### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by e0ipso** [RESTful-Drupal/restful_search_api#1]
To add information about:
- The filters.
- The facets.

**Comment by attiks** [comment]
Are facets already exposed on the API, and if so including a count for each term?

**Comment by e0ipso** [comment]
This needs a patch to restful that is going to land today.

**Comment by e0ipso** [comment]
@attiks see [this](https://medium.com/@e0ipso/restful-drupal-with-search-api-f370050a26bb) for more information about the facets integration.
