### ISSUE TITLE
Compatibility with Restful 2.x

### ISSUE THREAD

**Issue by justme7777** [RESTful-Drupal/restful_search_api#16]
Very interested in using this with Restful 2.x, using that at the moment and it works amazing.. 
But it seems like this is not compatible
Any plans on releasing a version for 2.x or do I have to use the 1.5 version of restful?

**Comment by e0ipso** [comment]
Have you tried the version `7.x-2.x`?

https://github.com/RESTful-Drupal/restful_search_api/tree/7.x-2.x

That should do it. :-)

**Comment by justme7777** [comment]
AS in::
  version 2.x, otherwise I am just going to pay to get the module ported
because Honestly, I think you guys made the best module I have ever seen in
drupal,!!!!
I mean this, I think this is the future for drupal!
Drupal is great for content management.... indexing and enterprise
resources! but the theme layer  is - well not the best-

Anywat BIG thumbs and I am willing to put some money in if needed!

2015-11-30 3:33 GMT+07:00 Mateu Aguiló Bosch notifications@github.com:

**Comment by e0ipso** [comment]
@justme7777 please, give restful_search_api:7.x-2.x a try. If you are missing any feature, maybe we can chat about that! :-)

Thank you for the kind words!
