### ISSUE TITLE
Pass trough not available in 2.x and example for reference

### ISSUE THREAD

**Issue by justme7777** [RESTful-Drupal/restful_search_api#18]
The pass_trough filter seems to be unavailable in version 2.x, (cannot find the function in the code either)

Also is there any example how to map references like taxonomy or entity references? 
EDIT: I assume these references need to be added to the search api index via related fields, however I cannot find out how to show these in the results (especially without pass through filter)
For example, in the index there is a taxonomy term for which I added the related field. This display's as follows in the fields tab of the index:

Province » Name    field_province:name

I cannot field a solution to get field_province:name to show up...
Thanks!

**Comment by e0ipso** [comment]
Pass through is deprecated. Use the `methods` array when declaring your public field.

I hope that helps.
