### ISSUE TITLE
Does the 7.x-1.x `restful_search_api` module works with 7.x-2.x `restful` module?

### ISSUE THREAD

**Issue by ckotwn** [RESTful-Drupal/restful_search_api#20]
Hi - thanks for this awesome module!

I am trying to create a search interface, but just noticed that the `restful` module has a major update to 2.x. I can get the `restful_example` module work by just replacing the module name. But the `restful_search_api_example` doesn't seem to work in the same way as `restful_example`.

So perhaps it worths a quick check with the authors. Does 1.x `restful_search_api` module work with 7.x-2.x `restful` module out-of-the-box?

**Comment by e0ipso** [comment]
It does not. 1.x works only with 1.x, and 2.x only with 2.x.

**Comment by ckotwn** [comment]
Thank you for clarifying!
