### ISSUE TITLE
Add 2x branch to drupal.org

### ISSUE THREAD

**Issue by drogers98** [RESTful-Drupal/restful_search_api#21]
First, thanks for a great module. Any chance 2x branch could be added to Drupal.org module page? Im specifying it as a dependency in a module build, and as it stands, users need to manually git clone the 2.x version, as drush can only access 1.x.

Cheers, and happy to help make this happen if desired.

Dan

**Comment by e0ipso** [comment]
I'm confused. I see it there...

**Comment by drogers98** [comment]
Thanks for the response @e0ipso. It's quite possible I'm missing something here, but I don't see it as an option either on the project page or via drush, screenshots:

Drush:
![screen shot 2016-04-20 at 7 17 25 am](https://cloud.githubusercontent.com/assets/3209424/14675873/4068be32-06c8-11e6-8fe5-c6f02c24b1a0.png)

Drupal.org:
![screen shot 2016-04-20 at 7 13 59 am](https://cloud.githubusercontent.com/assets/3209424/14675885/4f79323a-06c8-11e6-9d68-11ca8bb9ad14.png)

Cheers, and again, happy to help if I can. Thanks!

**Comment by e0ipso** [comment]
Sorry this took so long. This is done now.

**Comment by drogers98** [comment]
Thanks a ton, super appreciate it!
